### ISSUE TITLE
Problems with Submodules

### ISSUE THREAD

**Issue by tabouzeid** [mojohaus/versions-maven-plugin#113]
I'm using the versions plugin with the build-helper plugin to increment the version number on a specific submodule in a project that has many submodules. This is the command that i'm running

`mvn -pl my_submodule build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT`

it works but it throws this error:
```
[INFO] --- versions-maven-plugin:2.3:set (default-cli) @ project ---
[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: /project
[INFO] Processing change of project::1.0.4-SNAPSHOT -> 1.0.5-SNAPSHOT
[ERROR]
java.io.FileNotFoundException: /project/my_submodule/my_submodule (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:124)
	at org.codehaus.plexus.util.xml.XmlStreamReader.<init>(XmlStreamReader.java:67)
	at org.codehaus.plexus.util.ReaderFactory.newXmlReader(ReaderFactory.java:118)
	at org.codehaus.mojo.versions.api.PomHelper.readXmlFile(PomHelper.java:1606)
	at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.process(AbstractVersionsUpdaterMojo.java:321)
	at org.codehaus.mojo.versions.SetMojo.execute(SetMojo.java:298)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Processing project:my_submodule
[INFO]     Updating project project:my_submodule
[INFO]         from version 1.0.4-SNAPSHOT to 1.0.5-SNAPSHOT
[INFO]
```

**Comment by ribasco** [comment]
I'm facing the same issue for version 2.3 of the plugin. Rolling back to 2.1 does not throw this error. 

Also, the same issue was reported awhile back here [https://github.com/mojohaus/versions-maven-plugin/issues/44, ](url)

**Comment by fabiojb** [comment]
It seems that the change bdb3784d6fbb717604e0578f1402b43f4f5ec735 provoked the issue.
