### ISSUE TITLE
 versions:set on pom without <groupId> element causes NPE

### ISSUE THREAD

**Issue by stephenwiebe** [mojohaus/versions-maven-plugin#17]
If versions:set is invoked on a pom without a <groupId> element (in which case it inherits the groupId of its parent), an NPE results:

```
[14:03:59][Step 2/5] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.2:set (default-cli) on project spring-xre-application: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.2:set failed.
[14:03:59][Step 2/5] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
[14:03:59][Step 2/5] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[14:03:59][Step 2/5] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[14:03:59][Step 2/5] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[14:03:59][Step 2/5] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[14:03:59][Step 2/5] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[14:03:59][Step 2/5] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[14:03:59][Step 2/5] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
[14:03:59][Step 2/5] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
[14:03:59][Step 2/5] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[14:03:59][Step 2/5] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
[14:03:59][Step 2/5] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
[14:03:59][Step 2/5] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:03:59][Step 2/5] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:03:59][Step 2/5] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:03:59][Step 2/5] 	at java.lang.reflect.Method.invoke(Method.java:497)
[14:03:59][Step 2/5] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[14:03:59][Step 2/5] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[14:03:59][Step 2/5] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[14:03:59][Step 2/5] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[14:03:59][Step 2/5] Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.2:set failed.
[14:03:59][Step 2/5] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
[14:03:59][Step 2/5] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[14:03:59][Step 2/5] 	... 19 more
[14:03:59][Step 2/5] Caused by: java.lang.NullPointerException
[14:03:59][Step 2/5] 	at org.codehaus.mojo.versions.api.PomHelper.getModelEntry(PomHelper.java:1571)
[14:03:59][Step 2/5] 	at org.codehaus.mojo.versions.SetMojo.applyChange(SetMojo.java:275)
[14:03:59][Step 2/5] 	at org.codehaus.mojo.versions.SetMojo.execute(SetMojo.java:239)
[14:03:59][Step 2/5] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[14:03:59][Step 2/5] 	... 20 more
```

**Comment by lorijoan** [comment]
I think this makes sense because the parent can have a different groupID than the child.  Surely it is better to be explicit by needing the groupID in the case of them being the same rather than to inherit something incorrectly in the case of them being different and potentially have a silent failure?

**Comment by lorijoan** [comment]
Perhaps this is a duplicate though, it seems this was resolved already: https://github.com/mojohaus/versions-maven-plugin/issues/5  (And in your favour - I imagine separate differing groupID for parent & child is an anti-pattern then)

**Comment by stephenwiebe** [comment]
Yeah, looks like you're right - #5 is the same issue.
