### ISSUE TITLE
Can't update parent version when new param is introduced

### ISSUE THREAD

**Issue by dmitrytokarev** [mojohaus/versions-maven-plugin#201]
Update parent maven task fails on builds of projects that rely on parent when new parameter is introduced to parent which is used in the dependent projects …
`mvn versions:update-parent -DparentVersion=[${new-parent-ver}]`
Because maven tries to resolve all params from current version of parent (prior of actually updating it), but current version doesn't have new param and build fails.

*Reproduced on:*
```
JDK 1.8.121, 1.8.131
Maven 3.0.3, 3.3.9, 3.5.0
versions-maven-plugin 2.4
```

i had to write custom little script to update parent in python.
This works fine. The code could be simpler if using python `lxml` library but i don't control the env where the script runs, so built-in functions it is:
```python
import os

new_version = os.environ['new-parent-ver']  # look up new-parent-ver env var that is set for the build
lines = open('pom.xml').readlines()
enum_lines = enumerate(lines)
for i, l in enum_lines:
    if 'parent' in l:
        i, l = next(enum_lines)
        while 'version' not in l:
            i, l = next(enum_lines)
        print("Updating parent version from {0} to {1}".format(l.split('>')[1].split('<')[0], new_version))
        lines[i] = '\t\t<version>'+new_version+'</version>\n'
        break
open('pom.xml', 'w').writelines(lines)
```

**Comment by dmitrytokarev** [comment]
Build log with stacktrace:
```
Build log with stacktrace:
```
Branch 1.41.512 set up to track remote branch 512 from origin.

$ mvn -Dnew-parent-ver=1.0.512 versions:update-parent -DparentVersion=[${new-parent-ver}] -X -e

Apache Maven 3.0.3 (r1075438; 2011-02-28 09:31:09-0800)
Maven home: /var/build/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.0.3
Java version: 1.8.0_121, vendor: Oracle Corporation

[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /var/build/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.0.3/conf/settings.xml
[DEBUG] Reading user settings from /var/build/jenkins/.m2/settings.xml
[DEBUG] Using local repository at /var/build/jenkins/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /var/build/jenkins/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.company.team:platform:jar:1.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.datatype:jackson-datatype-joda:jar must be a valid version but is '${jackson-datatype-joda.version}'. @ line 109, column 16

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:339)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:632)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:581)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:233)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[ERROR]   
[ERROR]   The project com.company.team:platform:1.0-SNAPSHOT (/var/build/jenkins/workspace/platform-dev/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.datatype:jackson-datatype-joda:jar must be a valid version but is '${jackson-datatype-joda.version}'. @ line 109, column 16
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
Build step 'Invoke top-level Maven targets' marked build as failure
```

**Comment by dmitrytokarev** [comment]
Here is another stacktrace (a bit different on a diff env):
```
[platform-dev] $ /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.5.0/bin/mvn -DBRANCH=task-calendar-controls -DFORK=cm -Dmo-platform-parent-ver=1.$FORK.$BRANCH versions:update-parent -DparentVersion=[${mo-platform-parent-ver}] -X -e
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T19:39:06Z)
Maven home: /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.5.0
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /var/lib/jenkins/tools/hudson.model.JDK/JDK_8u121/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-514.26.2.el7.x86_64", arch: "amd64", family: "unix"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.fusesource.jansi.* < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Message scheme: color
[DEBUG] Message styles: debug info warning error success failure strong mojo project
[DEBUG] Reading global settings from /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.5.0/conf/settings.xml
[DEBUG] Reading user settings from /var/lib/jenkins/.m2/settings.xml
[DEBUG] Reading global toolchains from /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.5.0/conf/toolchains.xml
[DEBUG] Reading user toolchains from /var/lib/jenkins/.m2/toolchains.xml
[DEBUG] Using local repository at /var/lib/jenkins/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /var/lib/jenkins/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.company.team:platform:jar:1.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecycle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-core:jar must be a valid version but is '${fasterxml.version}'. @ line 76, column 13
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-databind:jar must be a valid version but is '${fasterxml.version}'. @ line 81, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-core:jar must be a valid version but is '${fasterxml.version}'. @ line 76, column 13
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-databind:jar must be a valid version but is '${fasterxml.version}'. @ line 81, column 13

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:382)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:400)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:391)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:78)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:511)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:221)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project com.company.team:platform:1.0-SNAPSHOT (/var/lib/jenkins/workspace/platform-dev/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-core:jar must be a valid version but is '${fasterxml.version}'. @ line 76, column 13
[ERROR]     'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-databind:jar must be a valid version but is '${fasterxml.version}'. @ line 81, column 13
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
Build step 'Invoke top-level Maven targets' marked build as failure
```

**Comment by khmarbaise** [comment]
Can you make a full example project...apart from that to be honest..I won't take Maven 3.0.3 into account cause it has to many bugs...the first of the line is Maven 3.0.5...Furthermore can you please check it on plain command line and inside Jenkins to be sure no influences are done by Jenkins Spies...just to be sure...

**Comment by dmitrytokarev** [comment]
Sure will do!
