### ISSUE TITLE
versions:set throws NullPointerException when I tried to set dependency version

### ISSUE THREAD

**Issue by kk30r** [mojohaus/versions-maven-plugin#235]
When I ran versions:set with "groupId", "artifactId" and "oldVersion" of dependency, the plugin throws exception.
I think org.codehaus.mojo.versions.SetMojo doesn't check null for "currnt" (L349).

```
Caused by: java.lang.NullPointerException
        at org.codehaus.mojo.versions.SetMojo.applyChange(SetMojo.java:359)
        at org.codehaus.mojo.versions.SetMojo.execute(SetMojo.java:328)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
```

**Comment by khmarbaise** [comment]
Which version of versions-maven-plugin have you used? Which version of Maven have you used?
 Can you please post the exact command line you have used?

**Comment by niklausxiao** [comment]
Hi @kk30r @khmarbaise  I met the same issue, full command line is `mvn versions:set -DgroupId=com.example -DartifactId=test -DoldVersion=1.0.0 -DnewVersion=1.0.1`
task failed:

> [ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.5:set (default-cli) on project flume-parent: Execution default-cli of goal or
g.codehaus.mojo:versions-maven-plugin:2.5:set failed. NullPointerException -> [Help 1]

stack is the same as @kk30r metioned.

**Comment by niklausxiao** [comment]
versions-maven-plugin version is 2.5
```
<plugin>
      <groupId>org.codehaus.mojo</groupId>
      <artifactId>versions-maven-plugin</artifactId>
      <version>2.5</version>
</plugin>
```

maven version is 3.3.3
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T19:57:37+08:00)
Maven home: D:\software\apache-maven-3.3.3
Java version: 1.8.0_72, vendor: Oracle Corporation
Java home: D:\Program Files\Java\jdk1.8.0_72\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by niklausxiao** [comment]
@khmarbaise I see you submit a new pr to fix this, what is this the root cause of this? Do we use it in a incorrect way ? or any workaround ?

**Comment by khmarbaise** [comment]
In the first place it should not throw a NPE at all.

**Comment by tarioch** [comment]
I'm hitting this error as well.
One thing to note is that the dependency is actually the parent.

So I have something like:

```xml
<parent>
<groupId>fooGroup</groupId>
<artifactId>fooArtifact</artifactId>
<version>12.0.1</version>
</parent>
```
and try to set this to a specific version which is not available (versions:update-parent unfortunately only works for versions which are available)

**Comment by johnstosh** [comment]
I'm using maven 3.0.5 and the command line
mvn -B -V -U versions:set -DgroupId=com.simuquest -DartifactId=cd-template -DoldVersion=[1.0,99.99] -DnewVersion=1.0.1.20836

and the NullPointerException shows up.

If I use * for the oldVersion like the following, then the NullPointerException doesn't happen.
mvn -B -V -U versions:set -DgroupId=com.simuquest -DartifactId=cd-template -DoldVersion=* -DnewVersion=1.0.1.20836


and this is the simple pom file:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
            
    <groupId>com.simuquest.cdimage</groupId>
    <artifactId>SimuQuest-QuantiPhiRE</artifactId>
    <version>1.3.1.19251</version>
    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>com.simuquest</groupId>
            <artifactId>cd-template</artifactId>
            <version>1.0.1.17627</version>
            <type>zip</type>
        </dependency>
         
    </dependencies>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
</project>

**Comment by johnstosh** [comment]
Hmm. Interesting.
It doesn't get the NullPointerException when using * for oldVersion, but it also doesn't change the pom file!

Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 08:51:28-0500)
Maven home: M:\apache-maven-3.0.5
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: M:\jdk1.8.0_131-64\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by samgabriel** [comment]
This occurs if you try to update the version of an artifact that is mentioned in a submodule but it is not listed on the root project. for example when using the war plugin to create an overlay. 

This is a blocker because if you try to call versions:set on the top level project you will get the NPE mentioned above. If you try to call versions:set on the specific sub module pom you will get an error that versions are managed from the root project. So the end result is that you can not possibly update the version of the artifact using this plugin. The commit 7ae79e6336d5c6debb8a285dc27419c6c4281b09 that was mentioned earlier should work but it is been pending for six month. Hopefully someone will merge it soon.

**Comment by mrdombie** [comment]
Looking forward to seeing this one go in.

**Comment by haridsv** [comment]
Any update on getting this merged?

**Comment by haridsv** [comment]
I actually hit the exact problem described by @samgabriel with plugin version 2.0, but when I tried version 2.7 and even 2.2, it worked fine.

**Comment by MarneusCalgarXP** [comment]
version 2.7, still happens :

$ mvn versions:use-releases  -X -e
...
Caused by: java.lang.NullPointerException
    at java.util.regex.Matcher.getTextLength (Matcher.java:1283)
    at java.util.regex.Matcher.reset (Matcher.java:309)
    at java.util.regex.Matcher.<init> (Matcher.java:229)
    at java.util.regex.Pattern.matcher (Pattern.java:1093)
    at org.codehaus.mojo.versions.UseReleasesMojo.useReleases (UseReleasesMojo.java:206)
    at org.codehaus.mojo.versions.UseReleasesMojo.update (UseReleasesMojo.java:100)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.process (AbstractVersionsUpdaterMojo.java:314)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.execute (AbstractVersionsUpdaterMojo.java:250)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)

**Comment by OnlyJeep** [comment]
> Hmm. Interesting. It doesn't get the NullPointerException when using * for oldVersion, but it also doesn't change the pom file!
> 
> Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 08:51:28-0500) Maven home: M:\apache-maven-3.0.5 Java version: 1.8.0_131, vendor: Oracle Corporation Java home: M:\jdk1.8.0_131-64\jre Default locale: en_US, platform encoding: Cp1252 OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

yes,i got the same problem,have u solved it?

**Comment by c3p0-maif** [comment]
Same problem here with provided dependencies which did not have versions specified 😞 
```
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:use-releases (default-cli) on project my-project: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.7:use-releases failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:use-releases (default-cli) on project my-project: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.7:use-releases failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.7:use-releases failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NullPointerException
    at java.util.regex.Matcher.getTextLength (Matcher.java:1770)
    at java.util.regex.Matcher.reset (Matcher.java:416)
    at java.util.regex.Matcher.<init> (Matcher.java:253)
    at java.util.regex.Pattern.matcher (Pattern.java:1133)
    at org.codehaus.mojo.versions.UseReleasesMojo.useReleases (UseReleasesMojo.java:206)
    at org.codehaus.mojo.versions.UseReleasesMojo.update (UseReleasesMojo.java:100)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.process (AbstractVersionsUpdaterMojo.java:314)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.execute (AbstractVersionsUpdaterMojo.java:250)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

```
<dependency>
  <groupId>org.projectlombok</groupId>
  <artifactId>lombok</artifactId>
  <scope>provided</scope>
</dependency>
```
