### ISSUE TITLE
NPE when dependencyManagement lacks a version

### ISSUE THREAD

**Issue by developingedan** [mojohaus/versions-maven-plugin#250]
I have run into an issue with the processing of the dependencyManagement section of a large super pom I am working on. I have the case where we need to control some exclusions at the parent level, but the version of the dependency in the project itself, so I have a dependencyManagement section that has a couple of dependency entries with just groupId, artifactId, and exclusions. We are running Maven 3.3.9. 

I have looked over the maven model xsd (minOccurs of version = 0 but then so is most everything else) and done some searching, and don't see anything explicitly saying this is a bad thing to do. 

Running any of the use-* goals (use-next-versions, etc), results in an NPE as the version does not exist. The actual error comes from maven-artifact, but it could be handled in AbstractVersionDetails or the Mojos themselves.

> [ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.5:use-next-versions (default) on project vl-sales-parent: Execution default of goal org.codehaus.mojo:versions-maven-plugin:2.5:use-next-versions failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.5:use-next-versions (default) on project vl-sales-parent: Execution default of goal org.codehaus.mojo:versions-maven-plugin:2.5:use-next-versions failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	**snip**
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.codehaus.mojo:versions-maven-plugin:2.5:use-next-versions failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.artifact.versioning.ComparableVersion.parseVersion(ComparableVersion.java:357)
	at org.apache.maven.artifact.versioning.ComparableVersion.<init>(ComparableVersion.java:348)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.parseVersion(DefaultArtifactVersion.java:112)
	at org.apache.maven.artifact.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:48)
	at org.codehaus.mojo.versions.api.AbstractVersionDetails.getNewerVersions(AbstractVersionDetails.java:249)
	at org.codehaus.mojo.versions.UseNextVersionsMojo.useNextVersions(UseNextVersionsMojo.java:101)
	at org.codehaus.mojo.versions.UseNextVersionsMojo.update(UseNextVersionsMojo.java:64)
	at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.process(AbstractVersionsUpdaterMojo.java:314)
	at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.execute(AbstractVersionsUpdaterMojo.java:250)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more

An example pom that shows the issue:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.sample</groupId>
  <artifactId>versions-error</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>


  <dependencyManagement>
	  <dependencies>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<!-- assume an exclusion list here -->
		</dependency>
	  </dependencies>
  </dependencyManagement>
  
  <dependencies>
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-lang3</artifactId>
		<version>3.6</version>
	</dependency>
  </dependencies>
</project>
```
And the command run
```
mvn org.codehaus.mojo:versions-maven-plugin:2.5:use-next-versions
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building versions-error 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.5:use-next-versions (default-cli) @ versions-error ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.149 s
[INFO] Finished at: 2018-01-03T15:55:02-05:00
[INFO] Final Memory: 12M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.5:use-next-versions (default-cli) on project versions-error: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.5:use-next-versions failed. NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by hypescript** [comment]
I've opened a PR #319 to fix this particular issue, but it's likely that other mojos are affected by the same problem.
