### ISSUE TITLE
Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:set (default-cli)

### ISSUE THREAD

**Issue by Zhenye-Na** [mojohaus/versions-maven-plugin#375]
The helper link in the log is as follows:

[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```
This error is reported in case the execution of a plugin failed due to some unforeseen event.
For example, uncatched runtime exceptions caused by the plugin will raise this error.
You should report this problem to the maintainer of the plugin.
```

Is there anything I can do to fix this error? Thank you so much for your help!

```
Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:set (default-cli) on project XXXXX: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.7:set failed. NullPointerException -> [Help 1]
```

**Comment by famod** [comment]
First, you should post the entire stacktrace (use `mvn -e ...`).

**Comment by Zhenye-Na** [comment]
Hi @famod , sorry for the confusion. This project is in Bamboo so I have enclosed the full stacktrace from Bamboo here. I hope this will help! I am new to this plugin! 

```
build	30-Dec-2019 14:58:21	[INFO] Error stacktraces are turned on.
build	30-Dec-2019 14:58:21	[INFO] Scanning for projects...
build	30-Dec-2019 14:58:23	[INFO] Downloading: http://server_url/artifactory/plugins-release/org/codehaus/mojo/versions-maven-plugin/maven-metadata.xml
build	30-Dec-2019 14:58:27	[INFO] Downloaded: http://server_url/artifactory/plugins-release/org/codehaus/mojo/versions-maven-plugin/maven-metadata.xml (856 B at 0.2 KB/sec)
build	30-Dec-2019 14:58:27	[INFO]                                                                         
build	30-Dec-2019 14:58:27	[INFO] ------------------------------------------------------------------------
build	30-Dec-2019 14:58:27	[INFO] Building project_name 1.0-SNAPSHOT
build	30-Dec-2019 14:58:27	[INFO] ------------------------------------------------------------------------
build	30-Dec-2019 14:58:28	[INFO] 
build	30-Dec-2019 14:58:28	[INFO] --- versions-maven-plugin:2.7:set (default-cli) @ edf ---
build	30-Dec-2019 14:58:41	[INFO] Searching for local aggregator root...
build	30-Dec-2019 14:58:41	[INFO] Local aggregation root: /usr/local/bamboo/bamboo_home/xml-data/build-dir/246317060-297959476
build	30-Dec-2019 14:58:41	[INFO] Processing change of com.xxx:1.0-SNAPSHOT -> release-5.11.5-2
build	30-Dec-2019 14:58:41	[INFO] ------------------------------------------------------------------------
build	30-Dec-2019 14:58:41	[INFO] BUILD FAILURE
build	30-Dec-2019 14:58:41	[INFO] ------------------------------------------------------------------------
build	30-Dec-2019 14:58:41	[INFO] Total time: 19.664 s
build	30-Dec-2019 14:58:41	[INFO] Finished at: 2019-12-30T14:58:41-08:00
build	30-Dec-2019 14:58:41	[INFO] Final Memory: 15M/170M
build	30-Dec-2019 14:58:41	[INFO] ------------------------------------------------------------------------
build	30-Dec-2019 14:58:41	[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:set (default-cli) on project edf: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.7:set failed. NullPointerException -> [Help 1]
build	30-Dec-2019 14:58:41	org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:set (default-cli) on project edf: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.7:set failed.
build	30-Dec-2019 14:58:41		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
build	30-Dec-2019 14:58:41		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
build	30-Dec-2019 14:58:41		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
build	30-Dec-2019 14:58:41		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
build	30-Dec-2019 14:58:41		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
build	30-Dec-2019 14:58:41		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
build	30-Dec-2019 14:58:41		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
build	30-Dec-2019 14:58:41		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
build	30-Dec-2019 14:58:41		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
build	30-Dec-2019 14:58:41		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
build	30-Dec-2019 14:58:41		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
build	30-Dec-2019 14:58:41		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
build	30-Dec-2019 14:58:41		at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
build	30-Dec-2019 14:58:41		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
build	30-Dec-2019 14:58:41		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
build	30-Dec-2019 14:58:41		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
build	30-Dec-2019 14:58:41		at java.lang.reflect.Method.invoke(Method.java:498)
build	30-Dec-2019 14:58:41		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
build	30-Dec-2019 14:58:41		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
build	30-Dec-2019 14:58:41		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
build	30-Dec-2019 14:58:41		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
build	30-Dec-2019 14:58:41	Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.7:set failed.
build	30-Dec-2019 14:58:41		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
build	30-Dec-2019 14:58:41		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
build	30-Dec-2019 14:58:41		... 20 more
build	30-Dec-2019 14:58:41	Caused by: java.lang.NullPointerException
build	30-Dec-2019 14:58:41		at org.codehaus.mojo.versions.SetMojo.applyChange(SetMojo.java:354)
build	30-Dec-2019 14:58:41		at org.codehaus.mojo.versions.SetMojo.execute(SetMojo.java:323)
build	30-Dec-2019 14:58:41		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
build	30-Dec-2019 14:58:41		... 21 more
build	30-Dec-2019 14:58:41	[ERROR] 
build	30-Dec-2019 14:58:41	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
build	30-Dec-2019 14:58:41	[ERROR] 
build	30-Dec-2019 14:58:41	[ERROR] For more information about the errors and possible solutions, please read the following articles:
build	30-Dec-2019 14:58:41	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
simple	30-Dec-2019 14:58:42	Failing task since return code of [/home/shared/env/apache-maven-3.3.9/bin/mvn -N -e -DnewVersion=release-5.11.5-2 -DartifactId=rt -DgroupId=com.inq versions:set] was 1 while expected 0
simple	30-Dec-2019 14:58:42	Finished task 'Update POMs to release version' with result: Failed
```
