### ISSUE TITLE
java.io.FileNotFoundException on running mvn versions:set

### ISSUE THREAD

**Issue by xoechts** [mojohaus/versions-maven-plugin#44]
After upgrading from 2.1 to 2.2 I get the following exception (reproducable)

```java
java.io.FileNotFoundException: D:\git\kern\kern-core-test\kern-core-test (The system cannot find the file specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:124)
        at org.codehaus.plexus.util.xml.XmlStreamReader.<init>(XmlStreamReader.java:67)
        at org.codehaus.plexus.util.ReaderFactory.newXmlReader(ReaderFactory.java:118)
        at org.codehaus.mojo.versions.api.PomHelper.readXmlFile(PomHelper.java:1613)
        at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.process(AbstractVersionsUpdaterMojo.java:319)
        at org.codehaus.mojo.versions.SetMojo.execute(SetMojo.java:251)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

My configuration is

```xml
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>versions-maven-plugin</artifactId>
                        <version>2.2</version>
                        <executions>
                            <execution>
                                <id>set release version</id>
                                <phase>validate</phase>
                                <goals>
                                    <goal>set</goal>
                                </goals>
                                <configuration>
                                    <newVersion>${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}.${jenkins.buildVersion}</newVersion>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
```

On a windows 10 machine using maven 3. The path from the error message does not exist.

**Comment by prostagma** [comment]
Are you using the -f or --file comand line parameters to specify an alternative pom file? 
If yes, versions:set doesn't suport this yet and there already is a pull request to resolve this, see the pull request [#27](https://github.com/mojohaus/versions-maven-plugin/pull/27).

**Comment by csdcrussell** [comment]
Ran into this today.  Is maybe related? https://github.com/mojohaus/versions-maven-plugin/issues/5

**Comment by ghilainm** [comment]
I have the same issue (duplicate the folder name at the end). I don't use any alternative pom.
However i am running the versions:set goal from a sub module. I have following structure.

pom.xml -> first aggreagator (not parent!)
####pom.xml -> second aggregator (not parent) -> running this:  mvn -o versions:set -DnewVersion=XXX -DprocessParent=false -D.allowSnapshots=true
#########pom.xml -> some module...
#########pom.xml -> some other module

**Comment by BuhTigRunner** [comment]
I have the same issue when use command  
**mvn --projects mod-auth versions:set -DnewVersion=111**
> 
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Mod Auth
[INFO] Token Verification
[INFO] Resource Protector
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Mod Auth 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.2:set (default-cli) @ mod-auth ---
[INFO] Searching for local aggregator root...
[INFO] Local aggregation root: C:\git\test-backend
[INFO] Processing change of com.example.test.auth:mod-auth:1 -> 2
[ERROR]
java.io.FileNotFoundException: C:\git\test-backend\mod-auth\mod-auth (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:124)
        at org.codehaus.plexus.util.xml.XmlStreamReader.<init>(XmlStreamReader.java:67)
        at org.codehaus.plexus.util.ReaderFactory.newXmlReader(ReaderFactory.java:118)
        at org.codehaus.mojo.versions.api.PomHelper.readXmlFile(PomHelper.java:1613)
        at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.process(AbstractVersionsUpdaterMojo.java:319)
        at org.codehaus.mojo.versions.SetMojo.execute(SetMojo.java:251)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Processing com.example.test.auth:mod-auth
[INFO]     Updating project com.example.test.auth:mod-auth
[INFO]         from version 1 to 2
[INFO]
[INFO] Processing com.motorolasolutions.vip.apigateway:apigateway
[INFO]     Updating dependency com.example.test.auth.resourceprotector:mod-auth-resource-protector
[INFO]         from version 1 to 2
[INFO]
[INFO] Processing com.example.test.auth.resourceprotector:mod-auth-resource-protector
[INFO]     Updating parent com.example.test.auth:mod-auth
[INFO]         from version 1 to 2
[INFO]     Updating project com.example.test.auth.resourceprotector:mod-auth-resource-protector
[INFO]         from version 1 to 2
[INFO]     Updating dependency com.example.test.auth.tokenverification:mod-auth-token-verification
[INFO]         from version 1 to 2
[INFO]
[INFO] Processing com.example.test.auth.tokenverification:mod-auth-token-verification
[INFO]     Updating parent com.example.test.auth:mod-auth
[INFO]         from version 1 to 2
[INFO]     Updating project com.example.test.auth.tokenverification:mod-auth-token-verification
[INFO]         from version 1 to 2
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Mod Auth .......................................... SUCCESS [  2.054 s]
[INFO] Token Verification ................................. SKIPPED
[INFO] Resource Protector ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.618 s
[INFO] Finished at: 2016-03-30T09:15:24+02:00
[INFO] Final Memory: 14M/222M
[INFO] ------------------------------------------------------------------------
> 

But if in the root pom file remove string **<module>mod-auth</module>** 
and  run:
**cd mod-auth** 
**mvn versions:set -DnewVersion=111**
all finished without exception.
If string **<module>mod-auth</module>** return back then exception reappears

**Comment by prostagma** [comment]
Can someone run the command with the -X switch?

**Comment by BuhTigRunner** [comment]
Yes i do. This is only important part
> 
[DEBUG] Looking for modules which use com.example.test.auth.resourceprotector                                                                             
[DEBUG] Processing mod-auth/token-verification as a parent.
[DEBUG] Looking for modules which use com.example.test.auth.tokenverification:mod-auth-token-verification  as their parent
[ERROR]
java.io.FileNotFoundException: C:\git\test-backend\mod-auth\mod-auth                                                                                                  
        (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:124)
        at org.codehaus.plexus.util.xml.XmlStreamReader.<init>(XmlStreamReader.java:67)
        at org.codehaus.plexus.util.ReaderFactory.newXmlReader(ReaderFactory.java:118)
        at org.codehaus.mojo.versions.api.PomHelper.readXmlFile(PomHelper.java:1613)
        at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.process(AbstractVersionsUpdaterMojo.java:319)
        at org.codehaus.mojo.versions.SetMojo.execute(SetMojo.java:251)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.514 s
[INFO] Finished at: 2016-03-31T10:02:38+02:00
[INFO] Final Memory: 13M/153M
>

**Comment by khmarbaise** [comment]
Can someone test that with the current SNAPSHOT version ?

**Comment by prostagma** [comment]
@khmarbaise Yes, I could simulate this error with the current SNAPSHOT, and I think I found the problem...

**Comment by atiyou** [comment]
i can reproduce the issue with 2.3 version (where app module depends on core, both as modules within the parent) : 
mvn -pl core,app versions:set -DnewVersion=X.X.X
apparently the 2.4-SNAPSHOT solves the issue 44, but there is another one !
The plugin only modify the version of the core module & the dependency of core in app, but not the app version itself!
Any idea ? when do you plan to release the 2.4 ?
