### ISSUE TITLE
Null Pointer Exception After Build Success

### ISSUE THREAD

**Issue by JKomoroski** [mojohaus/versions-maven-plugin#503]
Message and Trace:
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.187 s
[INFO] Finished at: 2021-11-09T08:59:50-07:00
[INFO] ------------------------------------------------------------------------
java.lang.NullPointerException
        at org.fusesource.jansi.AnsiPrintStream.uninstall(AnsiPrintStream.java:79)
        at org.fusesource.jansi.AnsiConsole.systemUninstall(AnsiConsole.java:530)
        at org.apache.maven.shared.utils.logging.MessageUtils.doSystemUninstall(MessageUtils.java:101)
        at org.apache.maven.shared.utils.logging.MessageUtils.systemUninstall(MessageUtils.java:80)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

Duplication Steps:

- Run the interactive command: `mvn versions:set`
- Enter your version when prompted.
- Wait for Success log.
- Stack Trace is printed and command exits with non-zero

Environment Information:
```
java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment 18.9 (build 11.0.13+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode, sharing)
```

```
mvn --version
Apache Maven 3.6.3 (Red Hat 3.6.3-12)
Maven home: /usr/share/maven
Java version: 11.0.13, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-1.fc35.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.14.15-300.fc35.x86_64", arch: "amd64", family: "unix"
```

I'm not sure if this is related to [https://issues.apache.org/jira/browse/MNG-7161]() or not.

**Comment by slawekjaranowski** [comment]
Please try with the latest Maven version.
I'm afraid that Maven community can't support your maven build by Red Hat

**Comment by khmarbaise** [comment]
I strongly recommend to try the Apache Maven (https://maven.apache.org/download.cgi) and retry your build with it. Also I recommend to upgrade to most recent version of Maven.

My experience with OS specific builds of Maven are simply leads to issues (because using different versions of libraries) (Ubuntu does that for example: https://stackoverflow.com/q/67481742/296328 etc.)

**Comment by JKomoroski** [comment]
Understood. I just thought it worth upstreaming my issue as a form of notification in case it hasn't been fixed.
