### ISSUE TITLE
issue while using versions:use-releases

### ISSUE THREAD

**Issue by KeerthiPattabhi** [mojohaus/versions-maven-plugin#92]
[INFO] [versions:use-releases {execution: default-cli}]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Unable to access unsupported property org.codehaus.stax2.preserveLocation
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.IllegalArgumentException: Unable to access unsupported property org.codehaus.stax2.preserveLocation
    at com.bea.xml.stream.ConfigurationContextBase.check(ConfigurationContextBase.java:98)
    at com.bea.xml.stream.ConfigurationContextBase.setProperty(ConfigurationContextBase.java:91)
    at com.bea.xml.stream.MXParserFactory.setProperty(MXParserFactory.java:250)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.newModifiedPomXER(AbstractVersionsUpdaterMojo.java:373)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.process(AbstractVersionsUpdaterMojo.java:320)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.execute(AbstractVersionsUpdaterMojo.java:257)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:79)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:618)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------

**Comment by khmarbaise** [comment]
Which maven version do you use? It looks like Maven 2.X? Really ? How have you called versions plugin on command line?

**Comment by KeerthiPattabhi** [comment]
Yes I use Maven version 2.2.1. I called it on command line as follows
mvn versions:use-releases

**Comment by khmarbaise** [comment]
Unfortunately I don't want to support Maven 2 anymore cause Maven 2 is [End of Life for a longer time](https://maven.apache.org/maven-2.x-eol.html). In contradiction I would go forward to Maven 3 only...Can you check this problem with Maven 3 as well if this happens also?
